name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with: 
          username: harshakastala
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v5.0.0
        with:
          push: true
          tags: harshakastala/Pythonapp:v1
