name: hello-world
on: 
  push: 
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with: 
          username: harshakastala
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Building Docker Image
        run: |
              docker build -t harshakastala/helloworld:${{ github.ref_name }}-${{ github.run_number }} -f ./Dockerfile .
      - name: Container Image
        run: |
              docker push harshakastala/helloworld:${{ github.ref_name }}-${{ github.run_number}}

      
      
