name: hello-world
on: 
  push: 
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with: 
          username: harshakastala
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v5.0.0
        with:
          push: true
          tags: harshakastala/helloworld:${{ github.ref_name }}-${{ github.run_number }}
